server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: xiaofeng-microservicecloud
  company.name: www.xiaofeng.com
  build.artifactId: microservicecloud-zuul-gateway-9527
  build.version: 1.0-SNAPSHOT

zuul:
  prefix: /xiao                                   #统一前缀
  ignored-services: microservicecloud-dept        #原真实服务名忽略，忽略多个时可用 "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**